### ISSUE TITLE
Proposed layout of fixtures

### ISSUE THREAD

**Issue by ahankinson** [OCFL/fixtures#2]
How's this for a proposed layout of the fixtures:

```
1.0/
  pass/
    test-01/
         ...
    test-02/
         ...
  fail/
  warn/
1.N/
```

**Comment by zimeon** [comment]
Certain agree with putting everything under the spec version number in parallel with the `spec` repo.

The pattern above looks like it is designed only for objects for validator tests? (given pass, fail, warn as key outcomes). I prefer to have some explanation in the test name as that makes life easier when wondering what and issue is. E.g. at the moment I have:

```
> ls -1 | grep -v json
bad00_empty
bad01_no_decl
bad02_no_id
bad03_no_inv
bad04_no_sidecar
```
So I would suggest something like this, but `s/bad/fail/` would be fine.

What about other fixtures such as data to build objects and they objects the correspond with? I think these are useful to tests of both packing and unpacking. I currently have these under `objects`, and `content`. If we have all objects together (with `fail`, `warn` and `pass` classes) then I suppose the current good objects would go in `pass` and we could have a `content` directory in parallel with data corresponding to things in `pass`?

**Comment by neilsjefferies** [comment]
For reference, 

1. There should be a bad object for each validation failure/warning type
2. There should be a good object for each possible starting point:
-  New V1
- New V01
- Inherited from MOAB
- Others?
3. There should be good objects representing each defined operation in Notes.

**Comment by zimeon** [comment]
Closing this now, we have:
```
fixtures/
├── 1.0
│   ├── bad-objects
│   ├── content
│   ├── good-objects
│   └── warn-objects
└── README.md
```

and are working toward adding error and warning codes in the text object names
